# Generated by Django 5.0.1 on 2024-02-06 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0002_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
