# Generated by Django 5.0.1 on 2024-02-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='approxweight',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
