# Generated by Django 5.0.1 on 2024-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='approxweight',
            field=models.BigIntegerField(),
        ),
    ]
