# Generated by Django 5.0.1 on 2024-02-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_alter_checkout_approxweight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='emial',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.TextField(max_length=255),
        ),
    ]
