# Generated by Django 5.0.1 on 2024-02-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_subcategory_sub_image'),
        ('customerapp', '0009_rename_emial_contactus_email_alter_contactus_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirmbooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.checkout')),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.deliveryboy')),
            ],
        ),
    ]
