# Generated by Django 5.0.1 on 2024-02-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0012_checkout_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='is_reject',
            field=models.BooleanField(default=False),
        ),
    ]
