# Generated by Django 5.0.1 on 2024-03-06 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rename_sub_image_subcategory_image'),
        ('customerapp', '0013_checkout_is_reject'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbooking',
            name='deliveryboy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.deliveryboy'),
        ),
    ]
