# Generated by Django 5.0.1 on 2024-04-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0015_alter_confirmbooking_deliveryboy'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmbooking',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
