# Generated by Django 5.0.1 on 2024-01-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_deliveryboy'),
    ]

    operations = [
        migrations.CreateModel(
            name='coustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('city', models.TextField()),
                ('phonenumber', models.BigIntegerField()),
            ],
        ),
    ]
