# Generated by Django 5.0.1 on 2024-01-30 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_deliveryboy_image_deliveryboy_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='deliveryboyimg/'),
        ),
        migrations.CreateModel(
            name='subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.categories')),
            ],
        ),
    ]
