# Generated by Django 5.0.1 on 2024-02-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_alter_deliveryboy_image_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='sub_image',
            field=models.ImageField(default=1, upload_to='sub_images'),
            preserve_default=False,
        ),
    ]
