# Generated by Django 5.0.1 on 2024-03-06 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_subcategory_sub_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='sub_image',
            new_name='image',
        ),
    ]
