# Generated by Django 5.0.1 on 2024-04-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_rename_sub_image_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryboy',
            name='adharnumber',
            field=models.ImageField(blank=True, null=True, upload_to='deliveryboyadharcard/'),
        ),
    ]
