# Generated by Django 5.0.1 on 2024-04-22 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0015_alter_confirmbooking_deliveryboy'),
        ('deliveryboyapp', '0002_confirmorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalbill',
            name='order_prod',
        ),
        migrations.AddField(
            model_name='finalbill',
            name='user',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Billingaddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('email', models.EmailField(max_length=220)),
                ('address', models.TextField(max_length=220)),
                ('phone', models.BigIntegerField(max_length=220)),
                ('other', models.CharField(max_length=220)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.checkout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
