# Generated by Django 5.0.1 on 2024-04-22 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryboyapp', '0003_remove_finalbill_order_prod_finalbill_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='final',
            field=models.ForeignKey(default=48, on_delete=django.db.models.deletion.CASCADE, to='deliveryboyapp.finalbill'),
            preserve_default=False,
        ),
    ]
